### ISSUE TITLE
Use native Enum class

### ISSUE THREAD

**Issue by thedrow** [5monkeys/django-enumfield#15]
Since 3.4 Python has a native Enum class.
It's backported [here](https://pypi.python.org/pypi/enum34).
Instead of a custom implementation those should be used.

**Comment by AncientSwordRage** [comment]
How is this coming along?

**Comment by thedrow** [comment]
I'm gonna try to implement it when I'm in London.
The next Django sprint will take place there.

**Comment by hashlash** [comment]
Any progress on this issue?

**Comment by kjagiello** [comment]
@hashlash No far from a release now https://github.com/5monkeys/django-enumfield/pull/48

**Comment by Swamii** [comment]
Implemented with #48
