### ISSUE TITLE
Does this work with Django 1.9?

### ISSUE THREAD

**Issue by somghosh** [5monkeys/django-enumfield#35]
I am seeing that it is supported till 1.8 as of late 2015 - is this working with 1.9 now?

**Comment by Godod** [comment]
@somghosh Hi. I'm using Django 1.9.6 and haven't problem with Enum

**Comment by sanbales** [comment]
This is not working for me on Django 1.9.

@Godod:  did you migrate from an older version or did you start clean with 1.9.6?

This is a snipped of the code that fails for me:
```
from django.db import models
from django_enumfield import enum
class VisibilityKind(enum.Enum):
    """HELP TEXT FOR VISILIBILITY KIND"""
    PRIVATE = 1
    PROTECTED = 2
    PUBLIC = 3
    PACKAGE = 4

    labels = {
        PRIVATE: 'private',
        PROTECTED: 'protected',
        PUBLIC: 'public',
        PACKAGE: 'package',
    }

class NamedElement(models.Model):
    visibility = enum.EnumField(VisibilityKind)
```

**Comment by Godod** [comment]
@sanbales I've started from django 1.9 and has been updated django every stable version. Now I have 1.9.8 and all ok with EnumField.

**Comment by sanbales** [comment]
@Godod thank you.  I'll try to figure out what is going on.  Cheers!

**Comment by jturmel** [comment]
Figure out what's wrong? I'm getting the same error too.

**Comment by vlordier** [comment]
@jturmel : pip install --pre django-enumfield==1.3b2 got me sorted with Django==1.9.9 and Python 3.4.3

**Comment by jturmel** [comment]
@vlordier that worked for me! Thanks.

**Comment by andreif** [comment]
Sorry folks, we'll push a stable update soon so it works without `--pre`.

**Comment by Swamii** [comment]
1.4 has been released. Please reopen if it doesn't work for any reason
