### ISSUE TITLE
Using Verbose_name

### ISSUE THREAD

**Issue by robertomorati** [5monkeys/django-enumfield#38]
Hi @hannseman ,

Is it possible set a verbose_name? How?

Example (way to do that):

```
field = enum.EnumField(..., verbose_name=_(u"......."), default=......)
```

I really appreciate the  attention.
Thanks,

**Comment by CarliJoy** [comment]
It is working for me with 
Django==2.2.6
django-enumfield==2.0b1

**Comment by Mojken** [comment]
This is a five year old question, maybe time to close the issue?
