### ISSUE TITLE
Field not refreshed with "refresh_from_db"

### ISSUE THREAD

**Issue by lamby** [5monkeys/django-enumfield#41]
It used to work in 1.9.6 , but I believe this commit in Django broke it:

   https://github.com/django/django/commit/7f51876f99851fdc3fef63aecdfbcffa199c26b9

It appears that the enumfield is not "concrete" as thus is not re-loaded.

**Comment by lamby** [comment]
Ah this is pretty much #39 …

**Comment by Swamii** [comment]
@lamby This should work when using version 1.4rc1

**Comment by lamby** [comment]
Thanks. Let's close for now then...
