### ISSUE TITLE
Supporting Django 2?

### ISSUE THREAD

**Issue by ADR-007** [5monkeys/django-enumfield#44]
Now it fails with error `AttributeError: module 'django.db.models' has no attribute 'SubfieldBase'`

**Comment by lengzuo** [comment]
Please use **pip install --pre django-enumfield==1.3b2** for Django >= 1.9.

**Comment by Swamii** [comment]
We don't officially support Django 2.0 yet (PRs welcome). 1.4rc1 might work, but it is not tested.

**Comment by Swamii** [comment]
Django 2.0 and 2.1 are now officially supported. Please open a new issue if there's any problems with it.
