### ISSUE TITLE
Advance sqlite version for testing

### ISSUE THREAD

**Issue by adrianparvino** [5monkeys/django-enumfield#50]
We're encountering a test failure due to `sqlmigrate`. The behavior change was introduced by [1].

[1] https://code.djangoproject.com/ticket/30023

**Comment by kjagiello** [comment]
Isn't this something you should fix on your side by bumping to the latest version of Django?

**Comment by adrianparvino** [comment]
Yeah, we're on a very recent django and a very recent sqlite, which is required for this behavior to exhibit.

```
[myrl@myrl:~]$ nix eval nixpkgs.sqlite.version
"3.28.0"

[myrl@myrl:~]$ nix eval nixpkgs.python3Packages.django_2_2.version
"2.2.4"
```

**Comment by adrianparvino** [comment]
My mistake, seems like with the latest django-enumfield, with the latest Django, this is a non-issue. OTOH, I believe

https://github.com/5monkeys/django-enumfield/blob/b9f549e90c3e42b886912c235ea1b34dcd172ab6/setup.py#L95

should be `install_requires=['typing;python_version<"3.7"']`?

**Comment by kjagiello** [comment]
Good catch! Will fix. Thanks!
