### ISSUE TITLE
django-enumfield is not Django 3.1rc1 compatible

### ISSUE THREAD

**Issue by pvergain** [5monkeys/django-enumfield#62]
Hi,

I'm using django 3.1rc1 and Python 3.8.5 and here is the problem. 
Do you plan a version for Django 3.1 ?

The classproperty has been moved from utils.decorators to utils.functional

- see https://github.com/django/django/commit/312049091288dbba2299de8d07ea3e3311ed7238#diff-2b7369f3709089e3ebcfdd6a4d3e3787

![image](https://user-images.githubusercontent.com/57228/88399380-143dc580-cdc7-11ea-92e3-a5ac5764bef0.png)

Thank you !

Have a nice day.

```
  from django_enumfield import enum
File "/opt/log_transaction/docker/.venv/lib/python3.8/site-packages/django_enumfield/enum.py", line 8, in <module>
  from django.utils.decorators import classproperty
container_django_transactions_colombie_dev | ImportError: cannot import name 'classproperty' from 'django.utils.decorators' (/opt/log_transaction/docker/.venv/lib/python3.8/site-packages/django/utils/decorators.py)
```

**Comment by ca-simone-chiorazzo** [comment]
Any news on this? We are stuck updating to Django 3 due to this problem.

**Comment by ca-simone-chiorazzo** [comment]
Any news on this? We are stuck updating to Django 3 due to this problem.

**Comment by zhavir** [comment]
Could you please provide any update on this issue please?

**Comment by hannseman** [comment]
2.0.2 was just released to PyPI. https://pypi.org/project/django-enumfield/2.0.2/

Thanks for your patience!
