### ISSUE TITLE
Import error in Django 4.0

### ISSUE THREAD

**Issue by StefanBrand** [5monkeys/django-enumfield#67]
```python
  File "/srv/service/my_project/my_feature/models.py", line 8, in <module>
    from django_enumfield.enum import Enum
  File "/usr/local/lib/python3.9/site-packages/django_enumfield/enum.py", line 15, in <module>
    from django_enumfield.db.fields import EnumField
  File "/usr/local/lib/python3.9/site-packages/django_enumfield/db/fields.py", line 8, in <module>
    from django.utils.encoding import force_text
ImportError: cannot import name 'force_text' from 'django.utils.encoding' (/usr/local/lib/python3.9/site-packages/django/utils/encoding.py)
```

[Features removed in 4.0](https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0)

**Comment by CapnKernel** [comment]
I'm also getting this.  It seems that `force_text` has been removed from Django 4.0, and replaced with `force_str`:

This package also has the same problem.

  https://stackoverflow.com/questions/70382084/import-error-force-text-from-django-utils-encoding/70390648

**Comment by thismatters** [comment]
There is also a similar issue with `ugettext`.

To mitigate this you can add the following monkeypatch to your `settings.py`:

```py
import django
from django.utils.encoding import force_str
django.utils.encoding.force_text = force_str
from django.utils.translation import gettext
django.utils.translation.ugettext = gettext
```

**Comment by PabloAlexis611** [comment]
I'm also seeing this error in one of my apps.

Django 4.0 Release Notes say:
- `django.utils.translation.ugettext()`, `ugettext_lazy()`, `ugettext_noop()`, `ungettext()`, and `ungettext_lazy()` are removed.
- `django.utils.encoding.force_text()` and `smart_text()` are removed.
